modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "mtr"
version = "@version@"
displayName = "Minecraft Transit Railway (PbtinaDev's Edition) [Unofficial Fork]"
authors = "Jonathan Ho - original author, PbtinaDev - unofficial fork maintainer"
description = '''
Unofficial fork of Minecraft Transit Railway.

This project is not affiliated with, endorsed by, or maintained by the original Minecraft Transit Railway developers.
'''
logoFile = "icon.png"

[[dependencies.mtr]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mtr]]
modId = "minecraft"
mandatory = true
versionRange = "[@minecraft@]"
ordering = "NONE"
side = "BOTH"