modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "mtr"
version = "@version@"
displayName = "Minecraft Transit Railway (PbtinaDev's Edition)"
authors = ["Jonathan Ho", "PbtinaDev (Fork)"]
description = "Un mod de Minecraft con sistemas de trenes automatizados."
logoFile = "icon.png"

[[dependencies.mtr]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mtr]]
modId = "minecraft"
mandatory = true
versionRange = "[@minecraft@]"
ordering = "NONE"
side = "BOTH"
